version: '3.8'

services:
  flask_app:
    image: lanirelad/push-event-logger:latest
    container_name: flask_app_container
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}  #  secret
    volumes:
      - flask-logs:/workingDir

volumes:
  flask-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/log/push-event-logger  # Path where your logs are stored