---
- name: Install necessary packages for Flask app
  apt:
    update_cache: yes

- name: Install Python and pip
  apt:
    name: 
      - python3
      - python3-pip
    state: present

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Git
  apt:
    name: git
    state: present

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose
  shell: |
    curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    chmod +x /usr/local/bin/docker-compose
  # args:
  #   warn: false

- name: Create a directory for logs on the host
  file:
    path: /var/log/push-event-logger 
    state: directory
    mode: '0755'
    owner: root
    group: docker

#  ---- housekipping 

- name: Stop and disable Flask app service if running
  systemd:
    name: flask-app
    state: stopped
    enabled: no
  ignore_errors: yes

- name: stop any process running on port 3000
  shell: fuser -k 3000/tcp || true
  ignore_errors: yes

- name: Remove any existing Docker container named flask-app
  docker_container:
    name: flask-app
    state: absent

- name: Wait for port 3000 to be released
  wait_for:
    port: 3000
    state: absent
    timeout: 10

- name: Pull Docker image for Flask app
  docker_image:
    name: lanirelad/push-event-logger
    tag: latest
    source: pull

- name: Run Flask app Docker container
  docker_container:
    name: flask-app
    image: lanirelad/push-event-logger:latest
    state: started
    #  restart_policy: always
    volumes:
      - /var/log/push-event-logger:/workingDir  
    ports:
      - "3000:3000"
    force: yes
    # recreate: true