# apache: |
#   {% if ansible_distribution == 'Ubuntu' %}
#   apache2
#   {% elif ansible_distribution == 'CentOS' %}
#   httpd
#   {% endif %}
# php: |
#   {% if ansible_distribution == 'Ubuntu' %}
#   libapache2-mod-php
#   {% elif ansible_distribution == 'CentOS' %}
#   php
#   {% endif %}

# msg: "This is a message from the provision site role"


# # # vars.yaml

# vars_by_distribution:
#   Ubuntu:
#     apache: apache2
#     php: libapache2-mod-php
#   CentOS:
#     apache: httpd
#     php: php
#   Debian:
#     apache: apache2
#     php: php7.4
#   # Add more distributions and their respective variables here


# # Set defaults if distribution is not listed
# distribution_vars: "{{ vars_by_distribution.get(ansible_distribution, {}) }}"


# # Set individual variables
# apache: "{{ distribution_vars.apache | default('unknown_apache') }}"
# php: "{{ distribution_vars.php | default('unknown_php') }}"

# msg: "This is a message from the provision site role"